# Generated by Django 5.1.1 on 2024-09-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('permite_recorrencia', models.BooleanField()),
                ('quantidade_recorrencia', models.IntegerField()),
                ('intervalo_recorrencia', models.IntegerField()),
                ('status_recorrencia', models.CharField(max_length=100)),
                ('agencia', models.IntegerField()),
                ('conta', models.IntegerField()),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
